name: CICD Pipeline 

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn compile
name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

  security_scan:
    runs-on: Agent-1     # Windows self-hosted runner
    needs: compile
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Security Scan
        id: security_scan
        uses: icantgetnosaticfaction/github-action-security-scan@v1
        with:
          github_token: ${{ secrets.Github-Action }}   # 👈 aapka custom secret

      - name: Output Results
        run: |
          echo "Critical Alerts: ${{ steps.security_scan.outputs.critical_count }}"
          echo "High Alerts: ${{ steps.security_scan.outputs.high_count }}"
          echo "Medium Alerts: ${{ steps.security_scan.outputs.medium_count }}"
          echo "Low Alerts: ${{ steps.security_scan.outputs.low_count }}"

      - name: Upload JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: security_scan_report
          path: ${{ steps.security_scan.outputs.high_critical_alerts_json }}

