name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile

  security-check:
    runs-on: Agent-1
    needs: compile

    steps:
      - uses: actions/checkout@v4

      # Install Trivy on Windows
      - name: Install Trivy
        run: |
          Invoke-WebRequest -Uri https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.55.0_Windows-64bit.zip -OutFile trivy.zip
          Expand-Archive trivy.zip -DestinationPath $Env:USERPROFILE\trivy
          echo "$Env:USERPROFILE\trivy" | Out-File -Append -FilePath $Env:GITHUB_PATH

      - name: Trivy FS Scan
        run: trivy fs --format table --output fs-report.json .

      # Install Gitleaks on Windows
      - name: Install Gitleaks
        run: |
          Invoke-WebRequest -Uri https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_8.18.4_windows_x64.zip -OutFile gitleaks.zip
          Expand-Archive gitleaks.zip -DestinationPath $Env:USERPROFILE\gitleaks
          echo "$Env:USERPROFILE\gitleaks" | Out-File -Append -FilePath $Env:GITHUB_PATH

      - name: Gitleaks Code Scan
        run: gitleaks detect --source . --report-format json --report-path gitleaks-report.json
